import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useBusiness } from "@/app/contexts/BusinessContext";
import { ApiClientRepository } from "@/app/core/infrastructure/repositories/ApiClientRepository";
import { GetClientsUseCase } from "@/app/core/application/use-cases/GetClientsUseCase";
import { CreateClientUseCase } from "@/app/core/application/use-cases/CreateClientUseCase";
import { useSnackbar } from "notistack";
import { Client } from "@/app/core/domain/entities/Client";
import { ClientFormData } from "../schemas/ClientSchema";

const clientRepository = new ApiClientRepository();
const getClientsUseCase = new GetClientsUseCase(clientRepository);
const createClientUseCase = new CreateClientUseCase(clientRepository);

export function useClients() {
  const { activeCompany, isLoadingContext } = useBusiness();
  const queryClient = useQueryClient();
  const { enqueueSnackbar } = useSnackbar();

  const { data: clients = [], isLoading, error, refetch } = useQuery({
    queryKey: ['clients', activeCompany?.id],
    queryFn: () => getClientsUseCase.execute(),
    enabled: !!activeCompany?.id && !isLoadingContext,
  });

  const createClientMutation = useMutation({
    mutationFn: (data: ClientFormData) => {
      if (!activeCompany?.id) throw new Error("No active company selected");
      
      return createClientUseCase.execute({
        id: "", // ID will be generated by the backend
        companyId: activeCompany.id,
        commercialName: data.commercialName,
        businessName: data.businessName,
        taxId: data.taxId,
        technicalContact: data.technicalContact,
        email: data.email,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['clients', activeCompany?.id] });
      enqueueSnackbar("Client created successfully", { variant: 'success' });
    },
    onError: (error: any) => {
      console.error("Error creating client:", error);
      enqueueSnackbar(error.message || "Error creating client", { variant: 'error' });
    }
  });

  return {
    clients,
    isLoading: isLoading || isLoadingContext,
    error,
    refetch,
    activeCompany,
    createClient: createClientMutation.mutateAsync,
    isCreating: createClientMutation.isPending
  };
}
